### PR TITLE
Wrong path for maps

### PR DESCRIPTION
**Pull request by that0n3guy**

### CODE REVIEW

**Comment by that0n3guy** [comment]
Also, this is actually unnecessary now.  You could just do something like: 
`-v /my_server/maps:/home/urt/UrbanTerror42/q3ut4/download` (I think the `download` directory I have there could be anything... thats just what I used) and the server will pick them up.  Makes startup faster b/c you don't have to copy all those map files.

In earlier versions of ut4 it may have been necessary, but now now.

**Comment by thomasleveil** [comment]
thx. Can you explain why this isn't necessary anymore? since which version?

**Comment by that0n3guy** [comment]
I have no idea what version, but its the same on the non-server (desktop).  You can put maps in a `q3ut4/download` folder and they are picked up by UT.

So essentially, if you put maps in that location (via docker volumes... no need to copy them) they work.  My server is running it right now.  

I tested putting them in the `q3ut4/maps` folder and that did NOT work.  Has to be the download folder.  Here is my docker compose yaml:

```
urt4:
  image: "tomdesinto/urbanterror:4.2.023"
  volumes:
    - "/data/urt4/q3ut4/:/q3ut4"
    - "/data/urt4/maps/:/home/urt/UrbanTerror42/q3ut4/download"
  ports:
    - "27960:27960/udp"
  expose:
    - "27960/udp"
```

**Comment by thomasleveil** [comment]
Could you make a pull request for that?

**Comment by that0n3guy** [comment]
Done, see: https://github.com/thomasleveil/docker-UrbanTerror/pull/2

**Pull request merged**
